services:
  bot:
    build:
      context: quote-bot-reborn
    depends_on:
      - mongodb
    volumes:
      - attachments:/usr/src/app/attachments/
    environment:
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-quote}
      - MONGODB_URI=mongodb://mongodb:mongodb@mongodb:27017
      - VK_TOKEN=${VK_TOKEN}

  backend:
    build:
      context: quote-site-reborn
    depends_on:
      - mongodb
    environment:
      - MONGODB_DB_NAME=${MONGODB_DB_NAME:-quote}
      - MONGODB_URI=mongodb://mongodb:mongodb@mongodb:27017
    volumes:
    - attachments:/usr/src/app/attachments/

  mongodb:
    image: mongo:5.0
    volumes:
      - mongodb-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb

  frontend:
    build:
      context: quote-site-frontend
      args:
        - MODE=${NGINX_MODE}
    depends_on:
      - backend
    ports:
      - ${HTTP_PORT:-80}:80
      - ${HTTPS_PORT:-443}:443
    volumes:
      - attachments:/data/attachments
      - ${SSL_CERTIFICATE:-./ssl/empty.crt}:/ssl/site.crt
      - ${SSL_CERTIFICATE_KEY:-./ssl/empty.key}:/ssl/site.key

volumes:
  mongodb-data:
  attachments:
